apiVersion: v1
kind: Service
metadata:
  name: example-nodeport
spec:
  type: NodePort
  selector:
    app: tinychat
  ports:
  - name: example-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31512
