apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplepage
  labels:
    app: simplepage
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: simplepage
  template:
    metadata:
      labels:
        app: simplepage
    spec:
      containers:
        - name: simplepage
          image: rhea31/simplepage:0.2
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
